version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./dbdata:/app/dbdata
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    restart: always

networks:
  nm_net:
    driver: bridge